name: nextcast
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.5.3
  http: ^1.4.0
  panara_dialogs: ^0.1.5
  geolocator: ^14.0.2
  smooth_page_indicator: ^1.2.1
  flutter_screenutil: ^5.9.3
  intl: ^0.19.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/clear-sky.png
    - Assets/drizzle.png
    - Assets/fog.png
    - Assets/LogoNoBg.png
    - Assets/partly-cloud.png
    - Assets/rain.png
    - Assets/snow.png
    - Assets/storm.png
    - Assets/Weather.gif
    - Assets/Weather2.gif
    - Assets/Weather3.gif

  fonts:
    - family: BebasNeue
      fonts:
        - asset: Fonts/BebasNeue-Regular.ttf
